command: robot -A C:\Users\udais\AppData\Local\Temp\RIDEdlzz7wba.d\argfile.txt --listener C:\Users\udais\AppData\Local\Programs\Python\Python310\lib\site-packages\robotide\contrib\testrunner\TestRunnerAgent.py:62717:False "D:\Robot Framework\My_Automation.robot"

TestRunnerAgent: Running under CPython 3.10.0

=========================================================================================
My Automation                                                                            
=========================================================================================

My First Testcase                                                                | PASS |
-----------------------------------------------------------------------------------------
My Automation                                                                    | PASS |
1 test, 1 passed, 0 failed
=========================================================================================
Debug:   D:\Robot Framework\Results\My Automation-Message-20241010-003921.log
Output:  D:\Robot Framework\Results\My Automation-Output-20241010-003921.xml
Log:     D:\Robot Framework\Results\My Automation-Log-20241010-003921.html

Report:  D:\Robot Framework\Results\My Automation-Report-20241010-003921.html



Test finished 20241010 00:39:26
